# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: fans
  joint_model_group_pose: p1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_b
    - joint3_propeller_l
    - joint2_propeller_l
    - joint1_propeller_l
    - joint3_propeller_r
    - joint2_propeller_r
    - joint1_propeller_r
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: fans_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_b
      - joint3_propeller_l
      - joint2_propeller_l
      - joint1_propeller_l
      - joint3_propeller_r
      - joint2_propeller_r
      - joint1_propeller_r
fans_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_b
    - joint3_propeller_l
    - joint2_propeller_l
    - joint1_propeller_l
    - joint3_propeller_r
    - joint2_propeller_r
    - joint1_propeller_r
  gains:
    joint_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_propeller_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2_propeller_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1_propeller_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_propeller_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2_propeller_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1_propeller_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1